apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blog
spec:
  selector:
    matchLabels:
      app: flask-blog
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-blog
    spec:
      containers:
      - name: flask-blog
        image: flask-blog:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000