apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-blog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-blog
  template:
    metadata:
      labels:
        app: flask-blog
    spec:
      containers:
      - name: flask-blog
        image: jaysalpatel/flask-blog:latest
        ports:
        - containerPort: 80
