apiVersion: v1
kind: Service
metadata:
  name: flask-blog-service
  spec: 
    selector:
      app: flask-blog
    ports:
    - protocol: "TCP"
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: v1
kind: Deployment
metadata:
  name: flask-blog
  spec:
    selector:
      matchLabels:
        app: flask-blog
      replicas: 2
      template: 
        metadata:
          labels:
            app: flask-blog
          spec: 
            containers:
            - name: flask-blog
            - image: flask-blog:latest
            imagePullPolicy: Never
            ports:
            - containerPort: 5000

















