apiVersion: v1
kind: Service
metadata:
  name: flask-blog-service
spec:
  selector:
    app: flask-blog
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blog
spec:
  selector:
    matchLabels:
      app: flask-blog
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-blog
    spec:
      containers:
      - name: flask-blog
        image: flask-blog:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
