version: '3.7'

services:
  web:
    build: ./flask-blog
    command: python flask-blog.py run -h 0.0.0.0
    volumes:
      - ./flask-blog/:/usr/src/app/
    ports:
      - 5000:5000
    env_file: 
      - ./.env.dev